version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: nobugs-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: nobugs-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped