package com.NoBugs.backend.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents the different roles a user can have within the NoBugs platform.
 * This entity maps to the `roles` table in the database.
 * Roles are used for access control (e.g., ADMIN, STUDENT, ORGANIZATION).
 */
@Data // Lombok: Generates getters, setters, toString, equals, and hashCode
@NoArgsConstructor // Lombok: Generates a no-argument constructor
@AllArgsConstructor // Lombok: Generates a constructor with all fields
@Entity // Marks this class as a JPA entity, mapped to a database table
@Table(name = "roles") // Specifies the table name for this entity in the database
public class Role {

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the primary key to be auto-generated by the database
    private Long id;

    @Column(nullable = false, unique = true, length = 50) // Maps to a database column; cannot be null, must be unique, max 50 chars
    private String name; // e.g., "ROLE_ADMIN", "ROLE_STUDENT", "ROLE_ORGANIZATION"
}
